<?php
/**
 * Vars: $errors[]
 */
?>

<?php if (!empty($errors)): ?>
<div class="alert alert-danger alert-dismissible mb-4">
    <div class="d-flex gap-2">
        <i class="ti ti-alert-circle fs-4 flex-shrink-0"></i>
        <div><?php foreach ($errors as $err): ?><div><?= e($err) ?></div><?php endforeach; ?></div>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<?php if (!vault_unlocked()): ?>
<div class="alert alert-warning mb-4">
    <i class="ti ti-lock me-1"></i>
    The vault must be unlocked before you can import a backup.
    <a href="<?= url('/vault/unlock') ?>" class="alert-link ms-1">Unlock Vault</a>
</div>
<?php endif; ?>

<div class="row justify-content-center">
    <div class="col-lg-7">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><i class="ti ti-database-import me-1"></i>Upload Backup File</h4>
            </div>
            <div class="card-body">

                <div class="alert alert-info mb-4">
                    <div class="d-flex gap-2">
                        <i class="ti ti-info-circle fs-4 flex-shrink-0"></i>
                        <div>
                            <strong>How import works:</strong> Records in the backup that already exist
                            in the database (matched by primary key) will be <em>skipped</em>. No existing
                            data will be overwritten. The vault must be unlocked to decrypt the backup file.
                        </div>
                    </div>
                </div>

                <form method="post" action="<?= url('/export/import') ?>"
                      enctype="multipart/form-data">
                    <?= csrf_field() ?>

                    <div class="mb-4">
                        <label class="form-label required">Backup File (.svbak)</label>
                        <input type="file" name="backup" class="form-control"
                               accept=".svbak,application/octet-stream" required>
                        <div class="form-text">
                            Only <code>.svbak</code> files generated by this application are supported.
                        </div>
                    </div>

                    <div class="d-flex gap-2">
                        <button type="submit" class="btn btn-success"
                                <?= !vault_unlocked() ? 'disabled' : '' ?>>
                            <i class="ti ti-upload me-1"></i>Upload &amp; Preview
                        </button>
                        <a href="<?= url('/export') ?>" class="btn btn-outline-secondary">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
