<?php
declare(strict_types=1);

namespace App\Controllers;

use App\Core\Controller;
use App\Core\View;
use App\Models\ClientModel;
use App\Models\M365BillingModel;
use App\Models\M365LicenseModel;
use App\Services\AuthService;

class M365Controller extends Controller
{
    public function __construct($request)
    {
        parent::__construct($request);
        M365LicenseModel::ensureSchema();
    }

    // ─── GET /m365 ────────────────────────────────────────────────────────────

    public function index(): void
    {
        // Auto-generate any overdue billing records (stacking)
        M365BillingModel::autoGenerateDue();

        $clientId = trim((string) $this->request->get('client_id', ''));
        $plan     = trim((string) $this->request->get('plan',      ''));
        $source   = trim((string) $this->request->get('source',    ''));
        $status   = trim((string) $this->request->get('status',    'active'));

        if (!in_array($status, ['active', 'inactive', 'all'], true)) $status = 'active';
        if (!in_array($source, ['', 'vendor', 'self'], true))         $source = '';

        $licenses = M365LicenseModel::getAll($clientId, $plan, $source, $status);
        $stats    = M365LicenseModel::getStats();

        View::share('pageActions',
            '<a href="' . url('/m365/create') . '" class="btn btn-primary">'
            . '<i class="ti ti-plus me-1"></i>Add License</a>'
        );

        $this->view('m365/index', [
            'title'       => 'M365 Licenses',
            'breadcrumbs' => [['label' => 'M365 Licenses']],
            'licenses'    => $licenses,
            'stats'       => $stats,
            'filters'     => compact('clientId', 'plan', 'source', 'status'),
            'allPlans'    => $this->buildPlans(),
            'clients'     => ClientModel::getForSelect(),
            'sources'     => M365LicenseModel::SOURCES,
            'sourceColors'=> M365LicenseModel::SOURCE_COLORS,
            'intervals'   => M365LicenseModel::INTERVALS,
        ]);
    }

    // ─── GET /m365/create ─────────────────────────────────────────────────────

    public function showCreate(): void
    {
        $this->view('m365/create', [
            'title'       => 'Add M365 License',
            'breadcrumbs' => [
                ['label' => 'M365 Licenses', 'url' => '/m365'],
                ['label' => 'Add License'],
            ],
            'clients'   => ClientModel::getForSelect(),
            'allPlans'  => $this->buildPlans(),
            'sources'   => M365LicenseModel::SOURCES,
            'intervals' => M365LicenseModel::INTERVALS,
        ]);
    }

    // ─── POST /m365/store ─────────────────────────────────────────────────────

    public function store(): void
    {
        $this->validateCsrf();

        $data   = $this->collectPost();
        $errors = $this->validate($data);

        if ($errors) {
            flash('error', implode(' ', $errors));
            flash('old', json_encode($data));
            $this->redirect('/m365/create');
        }

        $id = M365LicenseModel::create($data);

        AuthService::log(
            (int) $_SESSION['user_id'],
            'm365_license_created',
            'm365_license', $id,
            "M365 license created: {$data['plan']} for client #{$data['client_id']}",
            $this->request->ip(), $this->request->userAgent()
        );

        flash('success', 'M365 license added.');
        $this->redirect('/m365/' . $id);
    }

    // ─── GET /m365/{id} ───────────────────────────────────────────────────────

    public function show(): void
    {
        $license        = $this->findOr404();
        $billingRecords = M365BillingModel::getAllForLicense((int) $license['id']);

        $this->view('m365/show', [
            'title'          => e($license['client_name']) . ' — M365',
            'breadcrumbs'    => [
                ['label' => 'M365 Licenses', 'url' => '/m365'],
                ['label' => e($license['client_name'])],
            ],
            'license'        => $license,
            'billingRecords' => $billingRecords,
            'sources'        => M365LicenseModel::SOURCES,
            'sourceColors'   => M365LicenseModel::SOURCE_COLORS,
            'sourceIcons'    => M365LicenseModel::SOURCE_ICONS,
            'intervals'      => M365LicenseModel::INTERVALS,
        ]);
    }

    // ─── GET /m365/{id}/edit ──────────────────────────────────────────────────

    public function showEdit(): void
    {
        $license = $this->findOr404();

        $this->view('m365/edit', [
            'title'       => 'Edit M365 License',
            'breadcrumbs' => [
                ['label' => 'M365 Licenses', 'url' => '/m365'],
                ['label' => e($license['client_name']), 'url' => '/m365/' . $license['id']],
                ['label' => 'Edit'],
            ],
            'license'   => $license,
            'clients'   => ClientModel::getForSelect(),
            'allPlans'  => $this->buildPlans(),
            'sources'   => M365LicenseModel::SOURCES,
            'intervals' => M365LicenseModel::INTERVALS,
        ]);
    }

    // ─── POST /m365/{id}/update ───────────────────────────────────────────────

    public function update(): void
    {
        $this->validateCsrf();

        $license = $this->findOr404();
        $data    = $this->collectPost();
        $errors  = $this->validate($data);

        if ($errors) {
            flash('error', implode(' ', $errors));
            flash('old', json_encode($data));
            $this->redirect('/m365/' . $license['id'] . '/edit');
        }

        M365LicenseModel::update((int) $license['id'], $data);

        AuthService::log(
            (int) $_SESSION['user_id'],
            'm365_license_updated',
            'm365_license', (int) $license['id'],
            "M365 license updated: {$data['plan']} for client #{$data['client_id']}",
            $this->request->ip(), $this->request->userAgent()
        );

        flash('success', 'License updated.');
        $this->redirect('/m365/' . $license['id']);
    }

    // ─── POST /m365/{id}/delete ───────────────────────────────────────────────

    public function delete(): void
    {
        $this->validateCsrf();

        $license = $this->findOr404();

        M365LicenseModel::delete((int) $license['id']);

        AuthService::log(
            (int) $_SESSION['user_id'],
            'm365_license_deleted',
            'm365_license', (int) $license['id'],
            "M365 license deleted: {$license['plan']} for {$license['client_name']}",
            $this->request->ip(), $this->request->userAgent()
        );

        flash('success', 'License and all billing records deleted.');
        $this->redirect('/m365');
    }

    // ─── POST /m365/{id}/toggle ───────────────────────────────────────────────

    public function toggleActive(): void
    {
        $this->validateCsrf();

        $license   = $this->findOr404();
        $isNowActive = M365LicenseModel::toggleActive((int) $license['id']);
        $state     = $isNowActive ? 'activated' : 'deactivated';

        AuthService::log(
            (int) $_SESSION['user_id'],
            'm365_license_' . $state,
            'm365_license', (int) $license['id'],
            "M365 license {$state}: {$license['plan']}",
            $this->request->ip(), $this->request->userAgent()
        );

        flash('success', 'License ' . $state . '.');
        $this->redirect('/m365/' . $license['id']);
    }

    // ─── POST /m365/billing/{id}/pay ──────────────────────────────────────────

    public function markPaid(): void
    {
        $this->validateCsrf();

        $record = $this->findBillingOr404();
        M365BillingModel::markPaid((int) $record['id']);

        AuthService::log(
            (int) $_SESSION['user_id'],
            'm365_billing_paid',
            'm365_billing', (int) $record['id'],
            "M365 billing marked paid: {$record['period_label']} — {$record['client_name']}",
            $this->request->ip(), $this->request->userAgent()
        );

        flash('success', 'Billing period "' . $record['period_label'] . '" marked as paid.');
        $this->redirectAfterBilling($record);
    }

    // ─── POST /m365/billing/{id}/dismiss ──────────────────────────────────────

    public function dismiss(): void
    {
        $this->validateCsrf();

        $record = $this->findBillingOr404();
        M365BillingModel::dismiss((int) $record['id']);

        flash('success', 'Billing reminder dismissed.');
        $this->redirectAfterBilling($record);
    }

    // ─── POST /m365/billing/{id}/restore ──────────────────────────────────────

    public function restore(): void
    {
        $this->validateCsrf();

        $record = $this->findBillingOr404();
        M365BillingModel::restore((int) $record['id']);

        flash('success', 'Billing reminder restored to dashboard.');
        $this->redirect('/m365/' . $record['license_id']);
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    private function findOr404(): array
    {
        $id      = (int) $this->request->param('id', 0);
        $license = $id > 0 ? M365LicenseModel::getById($id) : null;

        if (!$license) {
            $this->notFound();
        }

        return $license;
    }

    private function findBillingOr404(): array
    {
        $id     = (int) $this->request->param('id', 0);
        $record = $id > 0 ? M365BillingModel::getById($id) : null;

        if (!$record) {
            $this->notFound();
        }

        return $record;
    }

    /**
     * After a billing action, redirect back to dashboard if the request
     * originated there, otherwise go to the license detail page.
     */
    private function redirectAfterBilling(array $record): void
    {
        $from = trim((string) $this->request->post('from', ''));
        $this->redirect($from === 'dashboard' ? '/dashboard' : '/m365/' . $record['license_id']);
    }

    /** Merge built-in plans with any custom plans already in the DB. */
    private function buildPlans(): array
    {
        $plans    = M365LicenseModel::BUILTIN_PLANS;
        $existing = M365LicenseModel::getDistinctPlans();

        foreach ($existing as $p) {
            if (!in_array($p, $plans, true)) {
                $plans[] = $p;
            }
        }

        return $plans;
    }

    private function collectPost(): array
    {
        $source   = trim((string) $this->request->post('license_source',   'vendor'));
        $interval = trim((string) $this->request->post('billing_interval', 'monthly'));

        if (!in_array($source,   ['vendor', 'self'],                    true)) $source   = 'vendor';
        if (!in_array($interval, ['monthly', 'quarterly', 'custom'],    true)) $interval = 'monthly';

        $amount   = round((float) str_replace(',', '', (string) $this->request->post('amount', '0')), 2);
        $seats    = max(1, (int) $this->request->post('seats', 1));
        $bDays    = max(1, (int) $this->request->post('billing_days', 30));
        $remDays  = max(0, (int) $this->request->post('remind_days',  5));

        return [
            'client_id'        => (int)   $this->request->post('client_id',        0),
            'plan'             => trim((string) $this->request->post('plan',        '')),
            'license_source'   => $source,
            'expiry_date'      => trim((string) $this->request->post('expiry_date', '')),
            'seats'            => $seats,
            'amount'           => $amount,
            'billing_interval' => $interval,
            'billing_days'     => $bDays,
            'remind_days'      => $remDays,
            'next_billing_date'=> trim((string) $this->request->post('next_billing_date', '')),
            'notes'            => trim((string) $this->request->post('notes',       '')),
        ];
    }

    private function validate(array $data): array
    {
        $errors = [];

        if ($data['client_id'] <= 0) {
            $errors[] = 'A client is required.';
        }

        if ($data['plan'] === '') {
            $errors[] = 'Plan name is required.';
        } elseif (mb_strlen($data['plan']) > 100) {
            $errors[] = 'Plan name must be 100 characters or fewer.';
        }

        if ($data['amount'] < 0) {
            $errors[] = 'Amount must be zero or greater.';
        }

        if ($data['expiry_date'] !== '' && strtotime($data['expiry_date']) === false) {
            $errors[] = 'Expiry date is not a valid date.';
        }

        if ($data['next_billing_date'] !== '' && strtotime($data['next_billing_date']) === false) {
            $errors[] = 'Next billing date is not a valid date.';
        }

        return $errors;
    }
}
